script:
- shellcheck kube-vagrant
before_deploy: tar -czvf kube-vagrant.tar.gz kube-vagrant LICENSE
deploy:
  provider: releases
  api_key:
    secure: RDtZbEi9bIJyilzDQpZFBFjA1zvU8w0nkU3EsuJUeV8TRgV7e7EYyNSbCgU6f5unDZ14BqAIL6ewQbbseGP7P+7Z084VRKl0LxZ4M497zGW0BNPek8wp1rysNnBD6OhdiqWSO6N0Oar5nzOp1NaxQjYyeXg+9WkMAC3iQBAMeaCQFPZF/f2IxloNS+QjuA1BJltjJVRHlxdeRRZtTPCilk1qxWeKwJgD6/qv1hRTpwdHwyywgTUE1vCGyJmi73yAr1rsitLOjAmJYuWaE6vrxpp9yQCjXyFzxYvTaK2K4u9INPUZvohtTSLheCsx6ZVZOKRLFBjVhRHvGew/mleNTmxs8AlOBBWpToYAkOffcyYzOcgPA5JSiSNjwqa10xQTlD3JIt5NBrIT4ojgd/Fc7yK0UxFl2Way1HvqVSdjkBPiVRgu56OT3tLo8llG87Xy0o9rO01d++1DfmXIOlDCFhP3EVKt/HR5jCS1bcn8AJ928Mn9ZAl1ZJ0/u8jiZcSv4ml9it7KTQIXTG7KtOAk+ocLRfh+yRMV/NkGmBtk3jGAZlmuz5cnVKrB6nwk5AMSDvx9F7KhD2UIJLCTk9pmYmpRr50DLZKf5TMAgpx59sWM6ibS/eEVujaaiQfzkXEr0JP4Ia7jkO0ahpYJtfsf5O+Q/0hOlB7DNxgeh77+7OQ=
  file: kube-vagrant.tar.gz
  on:
    repo: huazhihao/kube-vagrant
