script:
- shellcheck kube-vagrant
before_deploy: tar -czvf kube-vagrant.tar.gz kube-vagrant LICENSE
deploy:
  provider: releases
  api_key:
    secure: jchr03P9qW+2voQ2LJ7QGtaaYXU99eYF5so9TJWA8Y/6RMiQ5mtyhdjI14O2ios6A33TIL3vel20pz/Np4XJS1mi7vwcrRBrxKwOKZrMnwpvBqBYj07ZLWNz2LJlLKKGfyBQowQCX7Wq5JOUZtZIv9ge1k7SgDNT9aMGINyjLvdOibRxvM4RtoYxgFH0/ikVGdOzMihllYhIuVv4MuFS9TYREmwG9naENCP4l2WXIWZU05EaOEK+6fZrXMELS5rfmCD/+i7iN0sWleZQdEewWQq9xvGV6YdQqJo48DiHrNoRcEnPDd9qlBIj7XIa7msRy+QNl/OveqDy3T5JYOxCCzg7kv78IRXoU1PusPabS9pM1G+t79s4QdPHZnf/VYv4GGmhGDzwnbrmG1/UTSAGjzss6tGKn4WWmxygy3qXAqIXwJ18S6YYrAKp7GDdq0oe1bKU8N3hj3KmRrC5oqXFX08FHbOH13m9P4dUxW8Mg0op08mA1KTbm9tIHSb5JpleDiAzAorI+SsuXYgjKkDYUgMyNxKHUN76YsgaR+5xJ7Kdbke++mEVk+u9b2+KVKIir9LEJnzS668t9G+YSrxpUEpnHmZmrBaK7IxvXZepexxTy1UYJAm69ai1EejtPEN5Lu0rnmujd11CMogM8gGg1Thj7UUFz4ZoskiFwxfd+wE=
  file: kube-vagrant.tar.gz
  draft: false
  skip_cleanup: true
  on:
    repo: huazhihao/kube-vagrant
    tags: true
